---
version: "3"
services:
  frontend:
    image: akvo/akvo-node-14-alpine:20210106.152005.1864760
    ports:
      - 3000:3000
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
      - REACT_APP_CAPTCHA_KEY=${REACT_APP_CAPTCHA_KEY}
  backend:
    image: amancevice/pandas:0.24.2-slim
    ports:
      - 5000:5000
    environment:
      - BASIC_ADMIN=admin
      - BASIC_PWD=webform
      - FLOW_SERVICE_URL=${FLOW_SERVICE_URL}
      - AUTH0_USER=${AUTH0_USER}
      - AUTH0_PWD=${AUTH0_PWD}
      - AUTH0_URL=${AUTH0_URL}
      - AUTH0_CLIENT_FLOW=${AUTH0_CLIENT_FLOW}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ["./dev.sh"]
    volumes:
      - ./backend:/app:delegated
    working_dir: /app
