---
version: "3.9"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
  backend:
    image: amancevice/pandas:0.24.2-slim
    working_dir: /app
    command: ["./dev.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - BASIC_ADMIN=admin
      - BASIC_PWD=webform
      - FLOW_SERVICE_URL
      - AUTH0_USER
      - AUTH0_PWD
      - AUTH0_URL
      - AUTH0_CLIENT_FLOW
      # - SQLALCHEMY_DATABASE_URI
    # depends_on:
    #   - db
    network_mode: service:mainnetwork
  frontend:
    network_mode: service:mainnetwork
    image: akvo/akvo-node-17-alpine:20220121.024749.f30b815
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
      - REACT_APP_CAPTCHA_KEY
    depends_on:
      - backend
  # db:
  #   image: postgres:12-alpine
  #   volumes:
  #     - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #     - pg-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - 5432:5432
# volumes:
#   pg-data:
