---
version: "3"
services:
  mainnetwork:
    image: alpine:3.14.0
    command: ["tail", "-f", "/dev/null"]
  frontend:
    network_mode: service:mainnetwork
    image: akvo/akvo-node-14-alpine:20210106.152005.1864760
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      - REACT_APP_API_URL=http://localhost:3000/api
      - REACT_APP_CAPTCHA_KEY
  backend:
    network_mode: service:mainnetwork
    image: amancevice/pandas:0.24.2-slim
    environment:
      - BASIC_ADMIN=admin
      - BASIC_PWD=webform
      - FLOW_SERVICE_URL
      - AUTH0_USER
      - AUTH0_PWD
      - AUTH0_URL
      - AUTH0_CLIENT_FLOW
      - SQLALCHEMY_DATABASE_URI
    command: ["./dev.sh"]
    volumes:
      - ./backend:/app:delegated
    working_dir: /app
