---
apiVersion: v1
kind: Service
metadata:
  name: akvo-webform
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: akvo-webform
